# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - yourmindspace

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://yourmindspace.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_be52a68f378c43b8aae861b3e4bf89db }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bac84f12ed55445cbb25505330d339a0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: yourmindspace.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_be52a68f378c43b8aae861b3e4bf89db }}/stable:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'yourmindspace'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f2cd88523ba14af08cc168bda6aa3f40 }}
        images: 'yourmindspace.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_be52a68f378c43b8aae861b3e4bf89db }}/stable:${{ github.sha }}'